### ISSUE TITLE
code or *.DTA error?

### ISSUE THREAD

**Issue by mcdoans** [d-cogswell/MistrasDTA#2]
Hi @d-cogswell, this is such an awesome project! thanks for translating appendix II - Mistras's user manual to python code.
However, I encountered 3 type of problems when I tried to run the code to read my *.DTA files which confuse me whether I missed something during the installation, or my *.DTA files is not in the same format for what you've written. 

1. KeyError : 2

```
File c:\Users\Dy\06-AE\MistrasDTA.py:93, in read_bin(file, msg_id)
     91 # Look up byte length and read data values
     92 for CHID in CHID_list:
---> 93     b = CHID_byte_len[CHID]
     94       if b == 1:
     95       [v] = struct.unpack('B', data.read(b))

KeyError: 2
```

2. free variable 'test_start_time'

```
File c:\Users\Dy\06-AE\MistrasDTA.py:293, in <listcomp>(.0)
    288     rec = np.core.records.fromrecords(
    289         rec, names=['SSSSSSSS.mmmuuun', 'CH']+[CHID_to_str[i] for i in CHID_list])
    291     # Append a Unix timestamp field
    292     timestamp = [
--> 293         (test_start_time + timedelta(seconds=t)).timestamp()
    294         for t in rec['SSSSSSSS.mmmuuun']]
    295     rec = append_fields(rec, 'TIMESTAMP', timestamp,
    296                         usemask=False, asrecarray=True)
    298 if wfm:

NameError: free variable 'test_start_time' referenced before assignment in enclosing scope

```

3. KeyError : 1

```
File c:\Users\Dy\06-AE\MistrasDTA.py:267, in read_bin(file, msg_id)
    264 LEN = LEN-1
    266 MaxInput = 10.0
--> 267 Gain = 10**(gain[CID]/20)
    268 MaxCounts = 32768.0
    269 AmpScaleFactor = MaxInput/(Gain*MaxCounts)

KeyError: 1
```

Thanks in advance!

**Comment by d-cogswell** [comment]
Hi @mcdoans glad to hear you're using this code.

These errors seem to be from missing data which should have been found earlier in the file. Maybe your files have a slightly different structure from what I used for testing. Would you be willing to send me the files that aren't loading correctly? I can try to fix it.

**Comment by mcdoans** [comment]
I've sent u some data through a link to your email. thanks in advance!

**Comment by d-cogswell** [comment]
Thanks, it looks like your file has some hit characteristics which I did not implement. This should hopefully be easy to fix.

**Comment by mcdoans** [comment]
No, I think I am good without the RMS and signal strength. 
Regarding the parametric sensor, Yes, I am using the PCI-8 with 6 active channels for this experiment.

**Comment by d-cogswell** [comment]
I just pushed some changes that enable loading your files. Give it a try and let me know if it works.

Your files took ~3 minutes to load since they are so large. This could be reduced significantly if you don't care about reading the waveforms. I plan to add an optional argument to skip the waveforms.
