### ISSUE TITLE
A quick question for ’wfm‘ result

### ISSUE THREAD

**Issue by suboyangpolyu** [d-cogswell/MistrasDTA#4]
Dear Dr. Cogswell, 
Thank you for your wonderful contribution! A quick question: 
In MistrasDTA:
![image](https://github.com/user-attachments/assets/059cc6f8-6cb1-4ff5-ad67-a00fda2d3ef1)
In PAC manual:
![image](https://github.com/user-attachments/assets/9170b12c-5538-4b16-9776-985b0367b725)
The parameter 'TDLY' in ID-172,42 costs 2 bytes. The ‘wfm’ unpacking results will agree with AEwin-ASCII waveform output when I alter it.

**Comment by suboyangpolyu** [comment]
and 'B' to 'h', since it's negative in-built

**Comment by d-cogswell** [comment]
Hi @suboyangpolyu that's a good catch, I think you are right. I just created this fix: #5 . Can you help with some testing? I unfortunately don't have access to AEWin anymore.
